### ISSUE TITLE
 How the codesearch site built ?

### ISSUE THREAD

**Issue by Jamlee** [chromium/codesearch-py#29]
the new ui experience is great,  how to build the code search site ? :smile: , it is amazing for large project mangement.

**Comment by asankah** [comment]
Hi,

I assume you mean the codesearch backend? It is based on Kythe which comes
with a fairly good web frontend that is similar to the Chromium codesearch
site. You can find some examples at https://kythe.io/examples/.

**Comment by asankah** [comment]
I'll close this issue since it's not a bug report against codesearch-py. Please feel free to continue the discussion.
